### ISSUE TITLE
BDM | BUG | IE 11 Black background missing

### ISSUE THREAD

**Issue by mccoy-beacon** [beacondig/site-beacon#226]
**Location of bug**
Seen here: https://www.beacondigitalmarketing.com/sandbox-ebooks/ebook

On IE 11 the background is not showing the black background. Looks like there is a !important rule overriding:

![iexplore_2020-11-13_15-25-56.png](https://images.zenhubusercontent.com/5e9f48a441903e886529c043/e118daa8-a3a6-492e-8c6d-ee2ffd48b5dc)

I will check but I suspect this may be happening on other pages as well.

**Comment by dbeau79** [comment]
@mccoy-beacon this is because there is a background image that wasn't added when the post was published.  It's there now but the post is set to publish at a later date.  Here's a preview if you want to test again: 
https://www.beacondigitalmarketing.com/sandbox-ebooks/enviable-inspiring-inbound-marketing-campaign-ideas?hs_preview=uWHifnMu-37117886415
